apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsforge-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opsforge-api
  template:
    metadata:
      labels:
        app: opsforge-api
    spec:
      containers:
        - name: api
          image: mouadmodnibi/opsforge-api:6ac68fc4375ae27af9ff13c445fd10f5958a6253
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
