apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opsforge-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - opsforge.duckdns.org
      secretName: opsforge-tls
  rules:
    - host: opsforge.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opsforge-api-service
                port:
                  number: 80
